workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1

    ios-workflow:
      name: iOS Workflow 
  
      environment:
        ios_signing:
          distribution_type: app_store # or: ad_hoc | development | enterprise
          bundle_identifier: omega.TestDistribution
          
ios-native:
  environment:
    vars:
      BUNDLE_ID: "omega.TestDistribution"
      # XCODE_WORKSPACE: "CodemagicSample.xcworkspace" # <-- Name of your Xcode workspace
      XCODE_SCHEME: "TestDistribution" # <-- Name of your Xcode scheme
scripts:
  - name: Build ipa for distribution
    script: | 
      xcode-project build-ipa \
        --project "TestDistribution.xcodeproj" \
        --scheme "$XCODE_SCHEME"
artifacts:
  - build/ios/ipa/*.ipa
  - /tmp/xcodebuild_logs/*.log
  - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
  - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
