name: Build & upload to Firebase App Distribution 

on: 
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy: 

    runs-on: macOS-latest

    steps:
    - name: Getting the repo
      uses: actions/checkout@v3

    - name: build ios app
    - uses: yukiarrr/ios-build-action@v1.11.2
      with:
        project-path: Unity-iPhone.xcodeproj
        p12-base64: ${{ secrets.P12_BASE64 }}
        mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
        team-id: ${{ secrets.TEAM_ID }}
      
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: testers
        file: output.ipa
